### PR TITLE
Changed polyserve to polymer serve

### PR DESCRIPTION
**Pull request by scaratec**

### CODE REVIEW

**Review by addyosmani — APPROVED** [review]
LGTM. Have we checked there are no other side-effects of running `polymer serve` on the workflow here?

**Comment by scaratec** [comment]
I don't see there any issue. However, this the command that it is described on [polymer-project.org](https://www.polymer-project.org/1.0/start/first-element/intro) which is referring to this tutorial. So I find it necessary synchronize the description.

After all `polymer serve` is more up to date than `polyserve` I think.

**Comment by arthurevans** [comment]
LGTM.

**Comment by arthurevans** [comment]
Thanks for the PR!

**Pull request merged**
